controller_joint_names: ['', 'J1_L', 'J1_1', 'Cy1', 'J2_1', 'J1_U', 'J2_L', 'J1_2', 'Cy2', 'J2_2', 'J3_L', 'J1_3', 'Cy3', 'J2_3', 'J4_L', 'J1_4', 'Cy4', 'J2_4', 'J5_L', 'J1_5', 'Cy5', 'J2_5', 'J6_L', 'J1_6', 'Cy6', 'J2_6', ]
